version: '3.5'

services:
  docker-pupy:
    build: 20200417/
    container_name: docker-pupy
    restart: always
    ports:
      - "9000:9000"
      - "8443:8443"
    networks:
      pupy:

networks:
  pupy:
    driver: bridge

version: '3'