version: '3.5'

services:
  docker-pupy:
    image: cyb3rward0g/docker-pupy:20200415
    container_name: docker-pupy
    restart: always
    ports:
      - "9000:9000"
      - "8443:8443"
    networks:
      pupy:

networks:
  pupy:
    driver: bridge

version: '3'